# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time_spend',
            new_name='time_spent',
        ),
        migrations.AddField(
            model_name='event',
            name='properties',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AlterField(
            model_name='event',
            name='noun',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='verb',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Noun',
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
    ]
